# Generated by Django 4.2.13 on 2024-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0003_tipoprocedimiento_tipdescripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='casEstado',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('En Proceso', 'En Proceso'), (
                'Finalizada', 'Finalizada')], default='Solicitada', max_length=15),
        ),
    ]
